apiVersion: v1
kind: Secret
metadata:
  name: image-env
  namespace: paas
  labels:
    app: image
type: Opaque
data: 
  DELETE_CODE: "MQ=="
---
apiVersion: v1
kind: Secret
metadata:
  name: apollo-env
  namespace: paas
  labels:
    app: apollo
type: Opaque
data: 
  client_id: "MQ=="
  client_secret: "MTIz"
  MQ_USER: "cmViYml0"
  MQ_PASS: "cmViYml0"
---
apiVersion: v1
kind: Secret
metadata:
  name: prisma-env
  namespace: paas
  labels:
    app: prismagraphql
type: Opaque
data: 
  PRISMA_CONFIG: "ICAgIHBvcnQ6IDQ0NjYKICAgICMgdW5jb21tZW50IHRoZSBuZXh0IGxpbmUgYW5kIHByb3ZpZGUgdGhlIGVudiB2YXIgUFJJU01BX01BTkFHRU1FTlRfQVBJX1NFQ1JFVD1teS1zZWNyZXQgdG8gYWN0aXZhdGUgY2x1c3RlciBzZWN1cml0eQogICAgIyBtYW5hZ2VtZW50QXBpU2VjcmV0OiB0aGlzaXNzdXBlcnNlY3JldAogICAgZGF0YWJhc2VzOgogICAgICBkZWZhdWx0OgogICAgICAgIGNvbm5lY3RvcjogcG9zdGdyZXMKICAgICAgICBob3N0OiBwb3N0Z3JlcwogICAgICAgIHBvcnQ6IDU0MzIKICAgICAgICB1c2VyOiBwcmlzbWEKICAgICAgICBwYXNzd29yZDogcHJpc21hCiAgICAgICAgbWlncmF0aW9uczogdHJ1ZQo="
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-env
  namespace: paas
  labels:
    app: postgres
type: Opaque
data: 
  POSTGRES_USER: cHJpc21h
  POSTGRES_PASSWORD: cHJpc21h