apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: collab-db-backup
  namespace: backup
spec:
  schedule: 0 6 * * *
  concurrencyPolicy: Replace
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  suspend: false
  jobTemplate:
    metadata:
      labels:
        app: collab-mysqldump
    spec:
      backoffLimit: 1
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: mysqldump
            image: mariadb:10
            command: ["/bin/bash", "/scripts/script.sh"]
            envFrom:
            - secretRef:
                name: collab-mysqldump-env
            volumeMounts:
            - name: mysqldump-script
              mountPath: /scripts
            - mountPath: /backup
              name: mysqldump-volume
          volumes:
          - name: mysqldump-script
            configMap:
              name: collab-mysqldump-script
          - name: mysqldump-volume
            persistentVolumeClaim:
              claimName: collab-mysqldump-volume-claim
