apiVersion: v1
kind: Service
metadata:
  name: collab-db
  namespace: gccollab
spec:
  clusterIP: None
  ports: 
    - name: "mysql"
      protocol: TCP
      port: 3306
  selector: {}
---
kind: "Endpoints"
apiVersion: "v1"
metadata:
  name: "collab-db" 
  namespace: gccollab
subsets: 
- addresses:
  - ip: "10.0.0.1"
  ports:
  - name: "mysql"
    port: 3306