apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: collab-cron-weekly
  namespace: prod
spec:
  schedule: 0 6 * * *
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  suspend: false
  jobTemplate:
    metadata:
      labels:
        app: collab-cron-weekly
    spec:
      backoffLimit: 1
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: cron-weekly
            image: alpine:3.9
            command: ["/bin/curl", "/scripts/script-weekly.sh"]
            envFrom:
            - secretRef:
                name: collab-cron-weekly-env
            volumeMounts:
            - name: cron-weekly-script
              mountPath: /scripts
          volumes:
          - name: cron-weekly-script
            configMap:
              name: collab-cron-script
