apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: collab-cron-daily
  namespace: gccollab
spec:
  schedule: 0 5 * * *
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  suspend: false
  jobTemplate:
    metadata:
      labels:
        app: collab-cron-daily
    spec:
      backoffLimit: 1
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: cron-daily
            image: alpine:3.9
            command: ["/bin/sh", "/scripts/script-daily.sh"]
            volumeMounts:
            - name: cron-daily-script
              mountPath: /scripts
          volumes:
          - name: cron-daily-script
            configMap:
              name: collab-cron-script
