apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: collab-ingress
  namespace: gccollab
  annotations:
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: 2048m
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - gccollab.ca
    secretName: collab-secret
  rules:
  - host: gccollab.ca
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: collab
            port:
              number: 80
      - path: /cometchat
        pathType: ImplementationSpecific
        backend:
          service:
            name: goaway
            port:
              number: 8080
      - path: /cron
        pathType: ImplementationSpecific
        backend:
          service:
            name: goaway
            port:
              number: 8080
