apiVersion: v1
kind: ConfigMap
metadata:
  name: collab-mysqldump-script
  namespace: backup
  labels:
    app: collab-mysqldump
data:
  script.sh: |
    echo "Started backing up database"
    DATE=$(date +%Y%m%d%H%M%S)
    mysqldump --single-transaction -h "$MYSQL_HOST" -u$MYSQL_USR -p$MYSQL_PWD gccollab | gzip > /backup/${DATE}.sql.gz
    echo "Finished database backup"
