apiVersion: v1
kind: ConfigMap
metadata:
  name: collab-mysqldump-script
  namespace: backup
  labels:
    app: collab-mysqldump
data:
  script.sh: |
    echo "Started backing up database"
    DATE=$(date +%Y%m%d)
    BLOB_URL="https://${STORAGEACCOUNT}.blob.core.windows.net/collab-db/${DATE}.sql.gz?${SAS_TOKEN}"
    echo "getting curl and azcopy binary"
    apt-get update && apt-get install -y curl
    curl -o ./azcopy "https://${STORAGEACCOUNT}.blob.core.windows.net/backup-tools/azcopy?${AZCOPY_SAS_TOKEN}"
    echo "running mysqldump piped to azcopy"
    chmod +x ./azcopy
    mysqldump --single-transaction --ignore-table-data=gccollab.elggusers_sessions -h "$MYSQL_HOST" -u$MYSQL_USR -p$MYSQL_PWD gccollab | gzip | ./azcopy cp "${BLOB_URL}" --from-to PipeBlob
    echo "Finished database backup"

    if [ $(date --date='-30 days' +%d) == '01' ]
      then
        echo "not pruning monthly backup for $(date --date='-30 days' +%B)"
        exit
    fi
    echo "Pruning last month's backup"
    PRUNE_DATE=$(date --date='-30 days' +%Y%m%d)
    curl -X DELETE -H "x-ms-date: $(date -u)" "https://${STORAGEACCOUNT}.blob.core.windows.net/collab-db/$PRUNE_DATE.sql.gz?${SAS_TOKEN}"
