apiVersion: apps/v1
kind: Deployment
metadata:
  name: collab-solr
  namespace: collab-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collab-solr
  template:
    metadata:
      labels:
        app: collab-solr
    spec:
      containers:
      - name: solr
        image: solr:6
        ports:
        - containerPort: 8983
        readinessProbe:
          httpGet:
            path: /solr/admin/cores?action=status
            port: 8983
          initialDelaySeconds: 15
          periodSeconds: 90
          timeoutSeconds: 3
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /solr/admin/cores?action=status
            port: 8983
          initialDelaySeconds: 20
          periodSeconds: 90
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            memory: "1G"
            cpu: "0.5"
          limits:
            memory: "2Gi"
            cpu: "1"
        volumeMounts:
        - mountPath: /opt/solr/server/solr/mycores
          name: solr-data
      volumes:
      - name: solr-data
        persistentVolumeClaim:
          claimName: collab-solr-data-volume-claim-csi
---
apiVersion: v1
kind: Service
metadata:
  name: collab-solr
  namespace: collab-test
spec:
  clusterIP: None
  selector:
    app: collab-solr
  ports:
    - protocol: TCP
      port: 8983
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: collab-solr-data-volume-csi
  annotations:
    pv.kubernetes.io/provisioned-by: file.csi.azure.com
spec:
  capacity:
    storage: 50Gi
  persistentVolumeReclaimPolicy: "Retain"
  storageClassName: azurefile-csi
  accessModes:
    - ReadWriteMany
  csi:
    driver: file.csi.azure.com
    readOnly: false
    volumeHandle: collab-solr-data
    volumeAttributes:
      resourceGroup: aks
      shareName: solr
    nodeStageSecretRef:
      name: azure-secret
      namespace: default
  mountOptions:
    - dir_mode=0777
    - file_mode=0666
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: collab-solr-data-volume-claim-csi
  namespace: collab-test
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  volumeName: collab-solr-data-volume-csi
  resources:
    requests:
      storage: 50Gi
