apiVersion: v1
kind: Service
metadata:
  name: collab
  namespace: gccollab
  labels:
    app: collab
spec:
  ports:
    - protocol: TCP
      port: 80
  selector: 
    app: collab
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: collab-deployment
  namespace: gccollab
spec:
  #replicas: 3   # let the autoscaler handle this
  selector:
    matchLabels:
      app: collab
  template: # create pods using pod definition in this template
    metadata:
      annotations:
        config.linkerd.io/skip-outbound-ports: "3306"
      labels:
        app: collab
    spec:
      containers:
      - name: collab
        image: phanoix/gcconnex@sha256:d12ea139171e3cb622531143f4eb27a8d16edd02a896d3e16dd4b3095473496d
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /splash/
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /splash/
            port: 80
          initialDelaySeconds: 90
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        resources:
          requests:
            memory: "1024Mi"
            cpu: "0.7"
          limits:
            memory: "2048Mi"
            cpu: "0.85"
        env:
        - name: "DOCKER"
          value: ""
        - name: "HOME"
          value: "/var/www/html"
        - name: "DBHOST"
          value: "collab-db"
        - name: "WWWROOT"
          value: "http://gccollab.ca/"
        - name: "SOLR_CRAWLER"
          valueFrom:
            secretKeyRef:
              name: collab-env
              key: solr_crawler
        - name: "SOLR_CRAWLER_USER"
          value: "1706376"
        volumeMounts:
        - mountPath: /sites/gccollab_data
          name: collab-data-volume
        - mountPath: /sites/gccollab_data/views_simplecache
          name: views-simplecache
        - mountPath: /sites/gccollab_data/system_cache
          name: system-cache
        - mountPath: /var/www/html/engine/settings.php
          subPath: settings.php
          name: collab-settings
        - mountPath: /var/www/html/.htaccess
          subPath: htaccess
          name: collab-settings
      volumes:
      - name: collab-data-volume
        persistentVolumeClaim:
          claimName: collab-data-volume-claim
      - name: collab-settings
        configMap:
          name: collab-config
      - name: views-simplecache
        emptyDir: {}
      - name: system-cache
        emptyDir: {}
      nodeSelector:
        agentpool: collabpool
