kind: PersistentVolume
apiVersion: v1
metadata:
  name: dev-account-data-volume
  namespace: dev-account
spec:
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: "Retain"
  storageClassName: dev-account-data
  accessModes:
    - ReadWriteMany
  azureFile:
    secretName: azure-secret
    # a file share with this name needs to be created manually
    shareName: dev-account-data
    readOnly: false
  mountOptions:
    - dir_mode=0777
    - file_mode=0666
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dev-account-data-volume-claim
  namespace: dev-account
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: dev-account-data
  resources:
    requests:
      storage: 10Gi
---
# db volume
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dev-account-db-volume
  namespace: dev-account
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 1Gi