apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: account-db-backup
  namespace: backup
spec:
  schedule: 0 7 * * *
  concurrencyPolicy: Replace
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  suspend: false
  jobTemplate:
    metadata:
      labels:
        app: account-pgdump
    spec:
      backoffLimit: 1
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: pgdump
            image: postgres:10-alpine
            command: ["/bin/bash", "/scripts/script.sh"]
            envFrom:
            - secretRef:
                name: account-pgdump-env
            volumeMounts:
            - name: pgdump-script
              mountPath: /scripts
          volumes:
          - name: pgdump-script
            configMap:
              name: account-pgdump-script
