kind: PersistentVolume
apiVersion: v1
metadata:
  name: account-data-volume
  namespace: account
spec:
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: "Retain"
  storageClassName: account-data
  accessModes:
    - ReadWriteMany
  azureFile:
    secretName: azure-secret
    # a file share with this name needs to be created manually
    shareName: account-data
    readOnly: false
  mountOptions:
    - dir_mode=0777
    - file_mode=0666
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: account-data-volume-claim
  namespace: account
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: account-data
  resources:
    requests:
      storage: 10Gi
