kind: PersistentVolume
apiVersion: v1
metadata:
  name: account-pgdump-volume
  namespace: backup
spec:
  capacity:
    storage: 100Gi
  persistentVolumeReclaimPolicy: "Retain"
  storageClassName: account-db-backup
  accessModes:
    - ReadWriteMany
  azureFile:
    secretName: azure-secret
    # a file share with this name needs to be created manually
    shareName: account-db-backup
    readOnly: false
  mountOptions:
    - dir_mode=0777
    - file_mode=0666
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: account-pgdump-volume-claim
  namespace: backup
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: account-db-backup
  resources:
    requests:
      storage: 100Gi
