apiVersion: v1
kind: ConfigMap
metadata:
  name: account-pgdump-script
  namespace: backup
  labels:
    app: account-pgdump
data:
  script.sh: |
    echo "Started backing up database"
    DATE=$(date +%Y%m%d%H%M%S)
    pg_dump -h "$PGHOST" -U "$PGUSER" postgres | gzip > /backup/${DATE}.sql.gz
    echo "Finished database backup"
