apiVersion: v1
kind: Service
metadata:
  name: account
  namespace: account
spec:
  clusterIP: None
  ports:
    - protocol: TCP
      port: 8000
  selector: 
    app: account
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-deployment
  namespace: account
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: account
    spec:
      containers:
      - name: account
        image: phanoix/concierge@sha256:fc03885619421ccd5bce80e0a41ef56aca0095fd5ca4fc79a4021eb23fc9bf04
        ports:
        - containerPort: 8000
        env:
        - name: "DEBUG"
          value: "False"
        - name: "CONCIERGE_ALLOWED_HOSTS"
          value: '[''account.gccollab.ca'']'
        - name: "CONCIERGE_SECRET_KEY"
          valueFrom:
            secretKeyRef:
              name: account-env
              key: secret-key
        - name: "CONCIERGE_DATABASE_URL"
          valueFrom:
            secretKeyRef:
              name: account-env
              key: db-url
        - name: "EMAIL_USE_TLS"
          value: "True"
        - name: "SITE_URL"
          value: "https://account.gccollab.ca"
        livenessProbe:
          httpGet:
            path: /login
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 3
          timeoutSeconds: 1
          failureThreshold: 3
        resources:
          requests:
            memory: "128Mi"
            cpu: "0.05"
          limits:
            memory: "256Mi"
            cpu: "0.25"
        volumeMounts:
        - mountPath: /app/media
          name: account-data-volume
      volumes:
      - name: account-data-volume
        persistentVolumeClaim:
          claimName: account-data-volume-claim
---
apiVersion: v1
kind: Service
metadata:
  name: account-db
  namespace: account
spec:
  clusterIP: None
  ports: 
    - protocol: TCP
      port: 5432
  selector:
    app: account-db
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: account-db-deployment
  namespace: account
spec:
  replicas: 1 # tells deployment to run 1 pod matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: account-db
    spec:
      containers:
      - name: postgres
        image: postgres:10
        ports:
        - containerPort: 5432
        resources:
          requests:
            memory: "256Mi"
            cpu: "0.05"
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          subPath: postgresql-db
          name: account-db-volume
      volumes:
      - name: account-db-volume
        azureDisk:
          kind: Managed
          diskName: accountDBVolume
          diskURI: /subscriptions/{sub-id}/resourcegroups/{group-name}/providers/microsoft.compute/disks/accountDBVolume

