apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: wiki
  namespace: wiki
spec:
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: wiki-deployment