apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: wiki-db-backup
  namespace: wiki
spec:
  schedule: 0 7 * * *
  concurrencyPolicy: Replace
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  suspend: false
  jobTemplate:
    metadata:
      labels:
        app: wiki-mysqldump
    spec:
      backoffLimit: 1
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: mysqldump
            image: mariadb:10
            command: ["/bin/bash", "/scripts/script.sh"]
            envFrom:
            - secretRef:
                name: wiki-mysqldump-env
            volumeMounts:
            - name: mysqldump-script
              mountPath: /scripts
          volumes:
          - name: mysqldump-script
            configMap:
              name: wiki-mysqldump-script
