kind: PersistentVolume
apiVersion: v1
metadata:
  name: wiki-db-volume-csi
spec:
  capacity:
    storage: 32Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: "Retain"
  storageClassName: managed-csi
  accessModes:
    - ReadWriteOnce
  csi:
    driver: disk.csi.azure.com
    readOnly: false
    volumeHandle: /subscriptions/123/resourceGroups/RG/providers/Microsoft.Compute/disks/wiki-db-disk
    volumeAttributes:
      fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wiki-db-volume-claim
  namespace: wiki
spec:
  storageClassName: managed-csi
  accessModes:
    - ReadWriteOnce
  volumeName: wiki-db-volume-csi
  resources:
    requests:
      storage: 32Gi
