apiVersion: v1
kind: Service
metadata:
  name: wiki-db
  namespace: wiki
spec:
  clusterIP: None
  ports: 
    - protocol: TCP
      port: 3306
  selector:
    app: wiki-db
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: wiki-db-deployment
  namespace: wiki
spec:
  replicas: 1 # tells deployment to run 1 pod matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: wiki-db
    spec:
      containers:
      - name: mariadb
        image: mariadb:10.3
        ports:
        - containerPort: 3306
        env:
        - name: "MYSQL_ROOT_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: wiki-env
              key: db-root
        - name: "MYSQL_DATABASE"
          value: "wiki"
        - name: "MYSQL_USER"
          valueFrom:
            secretKeyRef:
              name: wiki-env
              key: db-user
        - name: "MYSQL_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: wiki-env
              key: db-password
        resources:
          requests:
            memory: "1Gi"
            cpu: "0.25"
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: wiki-db-volume
      volumes:
      - name: wiki-db-volume
        azureDisk:
          kind: Managed
          diskName: wikiDBVolume
          diskURI: 
