kind: PersistentVolume
apiVersion: v1
metadata:
  name: wiki-data-volume-csi
  annotations:
    pv.kubernetes.io/provisioned-by: file.csi.azure.com
spec:
  capacity:
    storage: 100Gi
  persistentVolumeReclaimPolicy: "Retain"
  storageClassName: azurefile-csi
  accessModes:
    - ReadWriteMany
  csi:
    driver: file.csi.azure.com
    readOnly: false
    volumeHandle: wiki-data
    volumeAttributes:
      resourceGroup: aks
      shareName: wiki-data
    nodeStageSecretRef:
      name: azure-secret
      namespace: default
  mountOptions:
    - dir_mode=0777
    - file_mode=0666
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wiki-data-volume-claim
  namespace: wiki
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  volumeName: wiki-data-volume-csi
  resources:
    requests:
      storage: 100Gi
