
resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "200m"
    memory: "1Gi"

metrics:
  enabled: true

service:
  type: LoadBalancer

persistence:
  enabled: true
  storageClass: managed-premium