
resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "100m"
    memory: "1Gi"

prometheus:
  exporter:
    enabled: true
  operator:
    enabled: false

service:
  type: LoadBalancer