apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: message-backup-prune
  namespace: default
spec:
  schedule: 0 7 * * *
  concurrencyPolicy: Replace
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  suspend: false
  jobTemplate:
    metadata:
      labels:
        app: message-backup-prune
    spec:
      backoffLimit: 1
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: backup-prune
            image: debian:jessie-slim
            command: ["/bin/bash", "/scripts/script.sh"]
            envFrom:
            - secretRef:
                name: message-backup-env
            volumeMounts:
            - name: backup-prune-script
              mountPath: /scripts
          volumes:
          - name: backup-prune-script
            configMap:
              name: message-backup-prune-script
