apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: message-db-backup
  namespace: message
spec:
  schedule: 0 7 * * *
  concurrencyPolicy: Replace
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  suspend: false
  jobTemplate:
    metadata:
      labels:
        app: message-backup
    spec:
      backoffLimit: 1
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: backup
            image: mongo:3
            command: ["/bin/bash", "/scripts/script.sh"]
            envFrom:
            - secretRef:
                name: message-backup-env
            volumeMounts:
            - name: backup-script
              mountPath: /scripts
          volumes:
          - name: backup-script
            configMap:
              name: message-backup-script
