apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-master-deployment
  namespace: message
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message
      rctype: master
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: message
        rctype: master
    spec:
      containers:
      - name: message
        image: rocketchat/rocket.chat:3.3.0
        ports:
        - containerPort: 8005
        env:
        - name: "INSTANCE_IP"
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: "PORT"
          value: "8005"
        - name: "ROOT_URL"
          value: "https://message.gccollab.ca/"
        - name: "MONGO_URL"
          value: "mongodb://message-db-mongodb-replicaset-0.message-db-mongodb-replicaset:27017,message-db-mongodb-replicaset-1.message-db-mongodb-replicaset:27017/rocketchat?replicaSet=rs0&readPreference=primaryPreferred"
        - name: "MONGO_OPLOG_URL"
          value: "mongodb://message-db-mongodb-replicaset-0.message-db-mongodb-replicaset:27017,message-db-mongodb-replicaset-1.message-db-mongodb-replicaset:27017/local?replicaSet=rs0"
        readinessProbe:
          httpGet:
            path: /api/info
            port: 8005
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 25
          failureThreshold: 7
        resources:
          requests:
            memory: "3Gi"
            cpu: "900m"
          limits:
            memory: "3Gi"
            cpu: "950m"
