apiVersion: v1
kind: Service
metadata:
  name: message
  namespace: prod
spec:
  clusterIP: None
  ports:
    - protocol: TCP
      port: 8005
  selector: 
    app: message
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: message-deployment
  namespace: prod
spec:
  replicas: 5
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: message
    spec:
      containers:
      - name: message
        image: rocketchat/rocket.chat:0.74.3
        ports:
        - containerPort: 8005
        env:
        - name: "INSTANCE_IP"
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: "PORT"
          value: "8005"
        - name: "ROOT_URL"
          value: "https://message.gccollab.ca/"
        - name: "DISABLE_PRESENCE_MONITOR"
          value: "yes"
        - name: "MONGO_URL"
          value: "mongodb://message-db-mongodb-replicaset-0.message-db-mongodb-replicaset:27017,message-db-mongodb-replicaset-1.message-db-mongodb-replicaset:27017/rocketchat?replicaSet=rs0&readPreference=primaryPreferred"
        - name: "MONGO_OPLOG_URL"
          value: "mongodb://message-db-mongodb-replicaset-0.message-db-mongodb-replicaset:27017,message-db-mongodb-replicaset-1.message-db-mongodb-replicaset:27017/local?replicaSet=rs0"
        readinessProbe:
          httpGet:
            path: /api/v1/info
            port: 8005
          initialDelaySeconds: 20
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            memory: "2Gi"
            cpu: "900m"
          limits:
            memory: "2560Mi"
            cpu: "950m"
        volumeMounts:
        - mountPath: /app/uploads
          name: message-data-volume
      volumes:
      - name: message-data-volume
        persistentVolumeClaim:
          claimName: message-data-volume-claim
