apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: naas-ingress
  namespace: naas
spec:
  tls:
  - hosts:
    - naas.test.phanoix.com
    secretName: naas-secret
  rules:
  - host: naas.test.phanoix.com
    http:
      paths:
      - path: /
        backend:
          serviceName: notification-apollo
          servicePort: 4000
